DirectoryIndex index.php

<Directory /var/www/html>
    AllowOverride All
    Require all granted
</Directory>

<Directory /var/www/html/storage>
    Require all denied
</Directory>

<Directory /var/www/html/data>
    Require all denied
</Directory>

<Directory /var/www/html/docker>
    Require all denied
</Directory>

<Directory /var/www/html/scripts>
    Require all denied
</Directory>

<FilesMatch "^\.env">
    Require all denied
</FilesMatch>
